project:
  type: book

book:
  title: "DSP Lecture Notes"
  author: "Nicolae Cleju"
  date: "12/14/2022"
  chapters:
    - index.qmd
    - 01_Intro.qmd
    - 04_FourierTransform.qmd
    - Shiny.qmd
    - references.qmd
    - part: "Solved Exercises"
      chapters:
      - Ex01_Sampling.qmd
      - Ex02_Systems.qmd
      - Ex03_Z_Transform.qmd
      - Ex04_Fourier.qmd
      # - 01_02_ProceseAleatoare.qmd
      # - 01_03_Autocorelatia.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  # PDF fails because of included .gif file
  # pdf:
  #   documentclass: scrreprt

jupyter: python3

filters:
  - shinylive

execute:
  cache: true
